package main

import (
	"fmt"
	"mapreduce"
	"os"
	"strconv"
	"log"
	"strings"
	"unicode"
	"unicode/utf8"
)

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
func mapF(filename string, contents string) []mapreduce.KeyValue {
	wordMap := make(map[string]int)

	ss := 0
	words := strings.Fields(contents)

	for _, word := range words {
		//word = strings.ToLower(word)
		if word[0:1] == "\"" {
			ss = ss + 1
		}
		preIndex := 0
		for index, char := range word {
			if !unicode.IsLetter(char)  {
				if preIndex < index {
					tmp := word[preIndex:index]
					wordMap[tmp] += 1
					ss += 1
				}
				preIndex = index + 1
			}
		}

		r, _ := utf8.DecodeRuneInString(word[len(word)-1:])

		if preIndex < len(word) && unicode.IsLetter(r) {
			tmp := word[preIndex:]
			wordMap[tmp] += 1
			ss += 1
		}
	}

	var result []mapreduce.KeyValue

	sum := 0
	for key := range wordMap {
		result = append(result, mapreduce.KeyValue{key, strconv.Itoa(wordMap[key])})
		sum += wordMap[key]
	}

	return result
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
func reduceF(key string, values []string) string {
	result := 0
	for _, value := range values {
		n, err := strconv.Atoi(value)
		if err != nil {
			log.Fatal("Can not convert ", value)
		}
		result += n
	}

	return strconv.Itoa(result)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
